version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: sis
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py makemigrations && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/home/app/webapp
    ports:
      - "8000:8000"
    depends_on:
      - db
