# Generated by Django 4.2.5 on 2023-10-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=50)),
                ('subject_name', models.CharField(max_length=100)),
                ('letter_grade', models.CharField(max_length=2)),
                ('points', models.FloatField()),
                ('credit', models.FloatField()),
                ('credit_points', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='AdditionalInfo',
        ),
    ]
