# Generated by Django 4.2.5 on 2023-10-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_studentmarks_delete_additionalinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('Semester 1', 'Semester 1'), ('Semester 2', 'Semester 2'), ('Semester 3', 'Semester 3'), ('Semester 4', 'Semester 4'), ('Semester 5', 'Semester 6'), ('Semester 6', 'Semester 6'), ('Semester 7', 'Semester 7')], max_length=20)),
                ('semester_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bus_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hostel_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('fine', models.DecimalField(decimal_places=2, max_digits=10)),
                ('examination_fees', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
